apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tribonacci
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: tribonacci
          kind: Service
          namespace: default
          port: 80
