apiVersion: v1
kind: Service
metadata:
  name: tribonacci
  namespace: default
  labels:
    app: tribonacci
spec:
  selector:
    app: tribonacci
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
