name: Deploy
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: cargo test
  build:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/neofight78/tribonacci:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Kubernetes apply
        run: |
          doctl kubernetes cluster kubeconfig show production > production-kubeconfig.yaml
          helm --kubeconfig=production-kubeconfig.yaml upgrade --install tribonacci ./helm/tribonacci --set image.tag=$GITHUB_SHA --set ingress.host=tribonacci.whoggarth.org
